# Generated by Django 3.1.4 on 2021-05-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0006_auto_20210428_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_failed',
            field=models.BooleanField(default=True),
        ),
    ]
