# Generated by Django 3.1.4 on 2021-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0007_task_is_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
